---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: bento/debian-8.1
    driver_config:
     network:
      - ['private_network', {ip: '172.16.1.5'}]

suites:
  - name: Apache
    run_list:
      - recipe[apache_softtek::default]
    attributes:
